Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: C:/Users/kon807152/Desktop/sky/sky_88.py =============
Traceback (most recent call last):
  File "C:/Users/kon807152/Desktop/sky/sky_88.py", line 27, in <module>
    d1=random.randint(1,100)
NameError: name 'random' is not defined
>>> 
============= RESTART: C:/Users/kon807152/Desktop/sky/sky_88.py =============
Traceback (most recent call last):
  File "C:/Users/kon807152/Desktop/sky/sky_88.py", line 34, in <module>
    t2.forward(d2)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1637, in forward
    self._go(distance)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1605, in _go
    self._goto(ende)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 3178, in _goto
    self._pencolor, self._pensize, top)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 545, in _drawline
    self.cv.coords(lineitem, *cl)
  File "<string>", line 1, in coords
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2469, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
>>> 
============= RESTART: C:/Users/kon807152/Desktop/sky/sky_88.py =============
Traceback (most recent call last):
  File "C:/Users/kon807152/Desktop/sky/sky_88.py", line 32, in <module>
    t1.forward(d1)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1637, in forward
    self._go(distance)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1605, in _go
    self._goto(ende)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 3178, in _goto
    self._pencolor, self._pensize, top)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 545, in _drawline
    self.cv.coords(lineitem, *cl)
  File "<string>", line 1, in coords
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2469, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
>>> 
============= RESTART: C:/Users/kon807152/Desktop/sky/sky_88.py =============
Traceback (most recent call last):
  File "C:/Users/kon807152/Desktop/sky/sky_88.py", line 43, in <module>
    t1.forward(d1)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1637, in forward
    self._go(distance)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 1605, in _go
    self._goto(ende)
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 3158, in _goto
    screen._pointlist(self.currentLineItem),
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\turtle.py", line 755, in _pointlist
    cl = self.cv.coords(item)
  File "<string>", line 1, in coords
  File "C:\Users\kon807152\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2469, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
>>> 
= RESTART: C:/Users/kon807152/AppData/Local/Programs/Python/Python37/aaaa.py =
Traceback (most recent call last):
  File "C:/Users/kon807152/AppData/Local/Programs/Python/Python37/aaaa.py", line 17, in <module>
    a1.goro(random.randint(-300,300),random.randint(-300,300))
AttributeError: 'Turtle' object has no attribute 'goro'
>>> 
= RESTART: C:/Users/kon807152/AppData/Local/Programs/Python/Python37/aaaa.py =
>>> 
